fix flash command

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -113,9 +113,14 @@ jobs:
           fi
 
           # look for documentation on flash and copy the command
-          command=`sed -n '/^Howto flash (esptool)$/,$p' ${DOC} | sed -n "/^## ${BOARD}\$/,${ n; n; p; }" | head -n1`
+          command=`sed -n '/^Howto flash (esptool)$/,$p' ${DOC} | sed -n "/^## ${BOARD}$/,\${ n; n; p; }" | head -n1`
 
-          echo "Command:"
+          if [ -z "$command" ]; then
+            echo "::error::Command not found in document ${DOC} for board ${BOARD}"
+            exit 1
+          fi
+
+          echo -n "Command: "
           echo "$command" | tee ${FILES}/flash.sh
           chmod a+x ${FILES}/flash.sh
 
